### ISSUE TITLE
The condition may change if there will be an official vanilla server.

### ISSUE THREAD

**Issue by mrk-han** [zerosnake0/Vanilla-WoW-AddOns#1]
>Currently I stopped playing vanilla WoW so the plugins here will NOT be updated. The condition may change if there will be an official vanilla server.

😄

**Comment by zerosnake0** [comment]
Sorry for the late reply.

Sadly, there is little time for me to play so...

**Comment by mrk-han** [comment]
No worries man! Cya around 👍
